export const Products_Mockeados = [
  {
    id: 1,
    category: "Comida",
    name: "Mekato variado",
    description: "Todo tipo de mekato desde bebidas a comestibles",
    price: "$10000",
    rating: 1,
    comments: 120,
    likes: 350,
    image: "/imghome/mekato.png",
  },
  {
    id: 2,
    category: "Producto",
    name: "Lociones",
    description: "Lociones artesanales con aromas natuarales",
    price: "$2000",
    rating: 2,
    comments: 89,
    likes: 230,
    image: "/imghome/lociones.png",
  },
  {
    id: 3,
    category: "Comida",
    name: "Galletas",
    description: "Galletas con chispas de chocolate",
    price: "$3000",
    rating: 3,
    comments: 156,
    likes: 420,
    image: "/imghome/cookies.png",
  },
  {
    id: 4,
    category: "Producto",
    name: "Manillas",
    description: "Manillas para portar con una persona especial",
    price: "$12000",
    rating: 4,
    comments: 75,
    likes: 180,
    image: "/imghome/nanillas.png",
  },
  {
    id: 5,
    category: "Servicio",
    name: "Clases de matematicas",
    description:
      "Clases de matematicas personalizadas primaria secundaria y universidad",
    price: "$200000",
    rating: 5,
    comments: 210,
    likes: 550,
    image: "/imghome/mate.png",
  },
];

export const noticias = [
  {
    id: 1,
    titulo: "TdeA ofertará Ingeniería Agronómica en 2025-I",
    descripcion: "El Ministerio de Educación Nacional otorgó registro calificado al programa de Ingeniería Agronómica del TdeA, al demostrar que reúne las condiciones de calidad exigidas por la ley",
    imagen: "/imgnotices/notice.png",
  },
  {
    id: 2,
    titulo: "Deportistas agradecieron al TdeA luego de su participación en Nacionales Universitarios",
    descripcion: "La delegación de deportistas TdeA, que participaron en los XXXI Juegos Universitarios Nacionales 2024 Ascun, propiciaron un acto de agradecimiento",
    imagen: "/imgnotices/deportistas.png",
  },
  {
    id: 3,
    titulo: "Invasión de gamers en el TdeA",
    descripcion: "Por cuarto año consecutivo se realizó el TdeA Gamer, el evento e-sports universitario más grande de Colombia n esta oportunidad la cita reunió a más de 300 jugadores de nueve instituciones de educación superior públicas y privadas.",
    imagen: "/imgnotices/gamers.png",
  },
  
];
